name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: "3.12"
  PACKAGE_NAME: "your_package_name"

jobs:
  version_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install pipenv
      run: pip install pipenv

    - name: Install dependencies
      run: pipenv install --dev

    - name: Run version check
      run: make version_check

  build:
    runs-on: ubuntu-latest
    needs: version_check
    if: github.event_name != 'pull_request'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install pipenv
      run: pip install pipenv

    - name: Cache pipenv
      id: pipenv-cache
      uses: actions/cache@v4
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv-

    - name: Install dependencies
      run: pipenv install --dev
      if: steps.pipenv-cache.outputs.cache-hit != 'true'

    - name: Build package
      run: pipenv run make build

    - name: Cache build
      uses: actions/cache@v4
      with:
        path: |
          dist
          build
          *.egg-info
        key: ${{ runner.os }}-build-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-build-

  lint_and_clean:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Restore build cache
      uses: actions/cache@v4
      with:
        path: |
          dist
          build
          *.egg-info
        key: ${{ runner.os }}-build-${{ github.sha }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install pipenv
      run: pip install pipenv

    - name: Install dependencies
      run: pipenv install --dev

    - name: Run linter
      run: pipenv run make lint

    - name: Clean up
      run: pipenv run make clean

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Restore build cache
      uses: actions/cache@v4
      with:
        path: |
          dist
          build
          *.egg-info
        key: ${{ runner.os }}-build-${{ github.sha }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install pipenv
      run: pip install pipenv

    - name: Install dependencies
      run: pipenv install --dev

    - name: Run tests
      run: pipenv run make test

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: ${{ github.event_name == 'pull_request' }}
        files: "./coverage.xml"

  release:
    runs-on: ubuntu-latest
    needs: [build, lint_and_clean, test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Restore build cache
      uses: actions/cache@v4
      with:
        path: |
          dist
          build
          *.egg-info
        key: ${{ runner.os }}-build-${{ github.sha }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install pipenv
      run: pip install pipenv

    - name: Install dependencies
      run: pipenv install --dev

    - name: Release package
      run: pipenv run make release
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
